site_name: CKB Learn
repo_url: https://github.com/ckb-learn/ckb-learn.github.io
edit_uri: edit/main/docs/
theme:
  name: material
  language: en
  custom_dir: theme
  features:
    - navigation.tabs

plugins:
  - i18n:
      default_language: en
      languages:
        en:
          name: English
        zh:
          name: 简体中文
      nav_translations:
        en:
          Kernel: "Kernel Developers"
        zh:
          Kernel: "内核开发者"
          Kernel Onboarding: "CKB 内核入门"
          Slides: "演示文稿"
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - index.md
  - Kernel:
    - Kernel Onboarding:
      - kernel/onboarding/index.md
      - "": kernel/onboarding/slides/ckb-kernel-introduction/index.md
      - "": kernel/onboarding/slides/ckb-cellbase/index.md
      - "": kernel/onboarding/slides/ckb-dynamic-difficulty-adjustment.md

extra_css:
  - stylesheets/extra.css

extra:
  reveal:
    path: reveal.js/dist
    transition: slide
    theme:
      name: white.css
      path: theme
    plugin:
      path: reveal.js/plugin
      menu:
        path: reveal.js-menu

  giscus:
    repo: "ckb-learn/ckb-learn.github.io"
    repo_id: !ENV GISCUS_REPO_ID
    category: "General"
    category_id: !ENV GISCUS_CATEGORY_ID
