site_name: CKB Learn
theme:
  name: material
  language: en
  custom_dir: theme

plugins:
  - search
  - i18n:
      languages:
        en: "English"
        zh: "简体中文"
      default_language: 'en'

extra:
  alternate:
    - name: English
      link: ""
      lang: en

    - name: 简体中文
      link: /index.zh/
      lang: zh

  reveal:
    path: reveal.js/dist
    transition: slide
    theme:
      name: white.css
      path: theme
    plugin:
      path: reveal.js/plugin
