site_name: CKB Learn
repo_url: https://github.com/ckb-learn/ckb-learn
edit_uri: edit/main/docs/
theme:
  name: material
  language: en
  custom_dir: theme
  features:
    - navigation.tabs

plugins:
  - search
  - tags
  - i18n:
      default_language: en
      languages:
        en:
          name: English
        zh:
          name: 简体中文
      nav_translations:
        en:
          Kernel: "Kernel Developers"
        zh:
          Kernel: "内核开发者"

nav:
  - index.md
  - Kernel:
    - kernel/onboarding/index.md

extra:
  reveal:
    path: reveal.js/dist
    transition: slide
    theme:
      name: white.css
      path: theme
    plugin:
      path: reveal.js/plugin

  giscus:
    repo: "ckb-learn/ckb-learn"
    repo_id: !ENV GISCUS_REPO_ID
    category: "General"
    category_id: !ENV GISCUS_CATEGORY_ID
